version: 2

updates:
  # Root monorepo
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 0
    groups:
      phpstan:
        patterns:
          - "phpstan/*"
      psalm:
        patterns:
          - "vimeo/psalm"
          - "psalm/*"
    labels:
      - "dependencies"
      - "php"

  - package-ecosystem: "composer"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "nextphp/core"

  - package-ecosystem: "composer"
    directory: "/packages/http"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "nextphp/http"

  - package-ecosystem: "composer"
    directory: "/packages/routing"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "nextphp/routing"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
